version: "3"
name: "frontend"

services:
  web:
    image: ingegno/dev/web
    command: sh -c "ng serve --host 0.0.0.0"
    build:
      context: ./web-ingegno
    volumes:
      - ./web-ingegno/www:/app/www
      - ./web-ingegno/src:/app/src
      - ./web-ingegno/firebase.json:/app/firebase.json
      - ./web-ingegno/.firebaserc:/app/.firebaserc
    ports:
      - 4200:4200
    environment:
      FIREBASE_TOKEN: you-token
      NODE_ENV: development
